name: make_better_defaults
channels:
  - defaults
dependencies:
  - pip
  - pip:
    - -e .  # conda >= 4.4 only
    - python-dotenv>=0.5.1
    - nbval
    - nbdime
    - gdown
  - setuptools
  - wheel
  - git>=2.5  # for git worktree template updating
  - sphinx
  - bokeh
  - click
  - colorcet
  - coverage
  - coveralls
  - matplotlib
  - jupyter
  - scikit-learn
  - scipy
  - joblib
  - nb_conda_kernels   # Try <2.2.0  if you hit nb_conda_kernels issue #158
  - pandas
  - requests
  - pathlib
  - fsspec
  - python=3.8

